# Configuración de Next.js para Netlify
# Optimizado para evitar errores de prerenderizado con autenticación y problemas de CSS
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_DISABLE_STATIC_GENERATION = "true"
  NEXT_PUBLIC_RUNTIME_ENV = "client"
  NODE_VERSION = "18.17.1"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true

# Redirecciones para SPA y para asegurar que los archivos estáticos se sirvan correctamente
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin", "owner", "member"]}
