module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        purple: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'spin': 'spin 1s linear infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-purple-50',
    'bg-purple-100',
    'bg-purple-200',
    'bg-purple-300',
    'bg-purple-400',
    'bg-purple-500',
    'bg-purple-600',
    'bg-purple-700',
    'bg-purple-800',
    'bg-purple-900',
    'text-purple-50',
    'text-purple-100',
    'text-purple-200',
    'text-purple-300',
    'text-purple-400',
    'text-purple-500',
    'text-purple-600',
    'text-purple-700',
    'text-purple-800',
    'text-purple-900',
    'border-purple-50',
    'border-purple-100',
    'border-purple-200',
    'border-purple-300',
    'border-purple-400',
    'border-purple-500',
    'border-purple-600',
    'border-purple-700',
    'border-purple-800',
    'border-purple-900',
    'hover:bg-purple-50',
    'hover:bg-purple-100',
    'hover:bg-purple-200',
    'hover:bg-purple-300',
    'hover:bg-purple-400',
    'hover:bg-purple-500',
    'hover:bg-purple-600',
    'hover:bg-purple-700',
    'hover:bg-purple-800',
    'hover:bg-purple-900',
    'focus:ring-purple-50',
    'focus:ring-purple-100',
    'focus:ring-purple-200',
    'focus:ring-purple-300',
    'focus:ring-purple-400',
    'focus:ring-purple-500',
    'focus:ring-purple-600',
    'focus:ring-purple-700',
    'focus:ring-purple-800',
    'focus:ring-purple-900',
    'animate-spin',
    'animate-pulse',
  ],
}
