/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-dark': 'var(--primary-dark)',
        'primary': 'var(--primary)',
        'primary-light': 'var(--primary-light)',
        'secondary': 'var(--secondary)',
        'secondary-light': 'var(--secondary-light)',
        'light-gray': 'var(--light-gray)',
        'gray': 'var(--gray)',
        'dark-gray': 'var(--dark-gray)',
        'success': 'var(--success)',
        'warning': 'var(--warning)',
        'error': 'var(--error)',
        'info': 'var(--info)',
      },
      fontFamily: {
        'sans': ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      boxShadow: {
        'outline': '0 0 0 3px rgba(58, 91, 188, 0.2)',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-primary-dark',
    'bg-primary',
    'bg-primary-light',
    'bg-secondary',
    'bg-secondary-light',
    'bg-light-gray',
    'bg-gray',
    'bg-dark-gray',
    'bg-success',
    'bg-warning',
    'bg-error',
    'bg-info',
    'text-primary-dark',
    'text-primary',
    'text-primary-light',
    'text-secondary',
    'text-secondary-light',
    'text-light-gray',
    'text-gray',
    'text-dark-gray',
    'text-success',
    'text-warning',
    'text-error',
    'text-info',
    'text-white',
    'border-primary-dark',
    'border-primary',
    'border-primary-light',
    'border-secondary',
    'border-secondary-light',
    'border-light-gray',
    'border-gray',
    'border-dark-gray',
    'border-success',
    'border-warning',
    'border-error',
    'border-info',
  ]
}
